services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: sql1
      MYSQL_DATABASE: petowner
      MYSQL_USER: rajaraman
      MYSQL_PASSWORD: sql1
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  mysql:

volumes:
  mysql_db:

#services:
#  postgres:
#    image: postgres
#    container_name: postgres
#    environment:
#      POSTGRES_USER: rajaraman
#      POSTGRES_PASSWORD: Psql@24
#      PGDATA: /data/postgres
#    volumes:
#      - postgres_data:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - postgres
#    restart: unless-stopped
#
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin_container
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    restart: unless-stopped
#
#networks:
#  postgres:
#    driver: bridge
#
#
#volumes:
#  postgres_data:
#  pgadmin_data:
