server:
  port: 8083

spring:
  application:
    name: GatewayServer
  zipkin:
    base-url: http//localhost:9411
  cloud:
    gateway:
      routes:
        - id: appointment
          uri: lb://APPOINTMENTSERVICE
          predicates:
            - Path=/api/v1/appointment/**
        - id: customer
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/api/v1/pet-owner/**


management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
